name: Build and Release on Push/PR

on: [push, pull_request]

permissions:
  contents: write

jobs:
  build_and_release:
    environment: DARKFY_DESKTOP_CLIENT 
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            script_suffix: linux
          - os: macos-latest
            script_suffix: mac
          - os: windows-latest
            script_suffix: win
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20 # Exemplo com LTS

    - name: Debug Environment Variables
      run: |
        echo "Verificando se as variáveis estão definidas (não mostrando valores)"
        echo "FIREBASE_API_KEY definido: ${{ secrets.FIREBASE_API_KEY != '' }}"
        echo "MINIO_ENDPOINT definido: ${{ secrets.MINIO_ENDPOINT != '' }}"
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # Solução específica para macOS
    - name: Configure GitHub token for npm
      if: matrix.os == 'macos-latest'
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
        echo "always-auth=true" >> .npmrc
        
    # Solução alternativa para o youtube-dl-exec no macOS
    - name: Pre-download youtube-dl binary for macOS
      if: matrix.os == 'macos-latest'
      run: |
        mkdir -p ./yt-dlp-cache
        curl -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -o ./yt-dlp-cache/yt-dlp https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp
        chmod +x ./yt-dlp-cache/yt-dlp
        echo "YT_DLP_BINARY_PATH=${{ github.workspace }}/yt-dlp-cache/yt-dlp" >> $GITHUB_ENV

    - name: Install dependencies
      run: npm ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Publish
      env:
          # Firebase
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          # Minio
          MINIO_ENDPOINT: ${{ secrets.MINIO_ENDPOINT }}
          MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
          MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
          MINIO_BUCKET_NAME: ${{ secrets.MINIO_BUCKET_NAME }}
          MINIO_USE_SSL: ${{ secrets.MINIO_USE_SSL }}
          # Token para publicação no GitHub
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # O script publish:(os) já faz o prepare:build
      run: |
        echo "Executando generate-config.js separadamente para debug"
        node generate-config.js
        echo "Executando script de publicação"
        npm run publish:${{ matrix.script_suffix }}